name: Compilar C

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compilar C code
        run: gcc Correlacion.c -o Correlacion -lm

      - name: Ejecutar programa
        run: echo "10\n1 2\n3 4\n5 6\n7 8\n9 10\n11 12\n13 14\n15 16\n17 18\n19 20" | ./Correlacion
