name: Compilar C

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compilar C code
        run: gcc Correlacion.c -o Correlacion -lm

      - name: Ejecutar programa
        run: echo "3 1 1 2 2 3 3" | ./Correlacion
